from usdNodeGraph.core.parameter.basic import Parameter
from .param_widget import *


Parameter.registerParameter(StringParameter, StringParameterWidget)
Parameter.registerParameter(ChooseParameter, ChooseParameterWidget)
Parameter.registerParameter(TokenParameter, StringParameterWidget)
Parameter.registerParameter(FilePathParameter, StringParameterWidget)
Parameter.registerParameter(AssetParameter, StringParameterWidget)
Parameter.registerParameter(TextParameter, TextParameterWidget)
Parameter.registerParameter(BoolParameter, BoolParameterWidget)

Parameter.registerParameter(IntParameter, IntParameterWidget)
Parameter.registerParameter(FloatParameter, FloatParameterWidget)
Parameter.registerParameter(DoubleParameter, FloatParameterWidget)

Parameter.registerParameter(Vec2fParameter, Vec2fParameterWidget)
Parameter.registerParameter(Vec3fParameter, Vec3fParameterWidget)
Parameter.registerParameter(Vec4fParameter, Vec4fParameterWidget)

Parameter.registerParameter(Vec2dParameter, Vec2fParameterWidget)
Parameter.registerParameter(Vec3dParameter, Vec3fParameterWidget)
Parameter.registerParameter(Vec4dParameter, Vec4fParameterWidget)

Parameter.registerParameter(Vec2hParameter, Vec2fParameterWidget)
Parameter.registerParameter(Vec3hParameter, Vec3fParameterWidget)
Parameter.registerParameter(Vec4hParameter, Vec4fParameterWidget)

Parameter.registerParameter(Color3fParameter, Vec3fParameterWidget)
Parameter.registerParameter(Point3fParameter, Vec3fParameterWidget)
Parameter.registerParameter(Normal3fParameter, Vec3fParameterWidget)

Parameter.registerParameter(QuatdParameter, Vec4fParameterWidget)
Parameter.registerParameter(QuatfParameter, Vec4fParameterWidget)
Parameter.registerParameter(QuathParameter, Vec4fParameterWidget)

Parameter.registerParameter(Matrix2dParameter, Matrix2dParameterWidget)
Parameter.registerParameter(Matrix3dParameter, Matrix3dParameterWidget)
Parameter.registerParameter(Matrix4dParameter, Matrix4dParameterWidget)

Parameter.registerParameter(TexCoord2fParameter, Vec2fParameterWidget)
Parameter.registerParameter(TexCoord2dParameter, Vec2fParameterWidget)
Parameter.registerParameter(TexCoord2hParameter, Vec2fParameterWidget)


Parameter.registerParameter(StringArrayParameter, TokenArrayParameterWidget)
Parameter.registerParameter(TokenArrayParameter, TokenArrayParameterWidget)
Parameter.registerParameter(IntArrayParameter, IntArrayParameterWidget)
Parameter.registerParameter(FloatArrayParameter, FloatArrayParameterWidget)
Parameter.registerParameter(DoubleArrayParameter, FloatArrayParameterWidget)
Parameter.registerParameter(Vec2fArrayParameter, Vec2fArrayParameterWidget)
Parameter.registerParameter(Vec3fArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(Vec4fArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(Vec2dArrayParameter, Vec2fArrayParameterWidget)
Parameter.registerParameter(Vec3dArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(Vec4dArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(Vec2hArrayParameter, Vec2fArrayParameterWidget)
Parameter.registerParameter(Vec3hArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(Vec4hArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(Color3fArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(Point3fArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(Normal3fArrayParameter, Vec3fArrayParameterWidget)
Parameter.registerParameter(QuatdArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(QuatfArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(QuathArrayParameter, Vec4fArrayParameterWidget)
Parameter.registerParameter(Matrix2dArrayParameter, Matrix2dArrayParameterWidget)
Parameter.registerParameter(Matrix3dArrayParameter, Matrix3dArrayParameterWidget)
Parameter.registerParameter(Matrix4dArrayParameter, Matrix4dArrayParameterWidget)
Parameter.registerParameter(TexCoord2fArrayParameter, Vec2fArrayParameterWidget)
Parameter.registerParameter(TexCoord2dArrayParameter, Vec2fArrayParameterWidget)
Parameter.registerParameter(TexCoord2hArrayParameter, Vec2fArrayParameterWidget)
